openapi: 3.0.0
info:
  version: 1.0.0
  title: Ti.Me.EvaluationAPI
  description: "APIサーバーでの値の引き渡し、静的ファイル系はフロントで完結。"
tags:
  - name: point

paths:
  /search:
    get:
      summary: 場所候補の検索
      description: ユーザーが文字列検索をし、場所の複数候補を受け取る
      tags:
        - point
      parameters:
        - in: query
          name: query-place
          schema: 
            type: string
          description: 入力した地名(場所名)
      responses:
        '200':
          description: "検索結果が1件以上の場合"
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/SearchGetResponse"
        default:
          description: "検索候補が0件の場合 or 検索候補が10件より上の場合 などのエラー"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /measure:
    get:
      summary: 地点もとに計測
      description: 地点もとに時間と距離を計測して返す。=> 時間と距離の計測と描画は非同期でええな。
      tags:
        - point
      requestBody:
        description: "地点の配列"
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/MeasureGetRequest"
      responses:
        '200':
          description: "検索結果が1件以上の場合"
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/MeasureGetResponse"
        default:
          description: "地点の配列が0,1件の場合などのエラー ex) 削除して検索"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  schemas:
    SearchGetResponse:
      type: object
      required:
        - results
      properties:
        results:
          type: array
          items:
            type: object
            required:
              - location
              - address
              - name
            properties:
              location:
                type: object
                required:
                - lat
                - lng
                properties:
                  lat:
                  # 小数点
                    type: number
                  lng:
                    type: number
              address:
                type: string
              name:
                type: string

    MeasureGetRequest:
      type: object
      required:
        - from
        - to
        - betweens
      properties:
        from:
          type: string
        to: 
          type: string
        betweens:
          type: array
          items:
            type: object
            required:
              - point
              - order
            properties:
              point:
                type: string
              order:
                type: integer 


    MeasureGetResponse:
      type: object
      required:
        - results
      properties:
        results:
          type: array
          items:
            type: object
            required:
              - start_location
              - end_location
              - start_address
              - end_address
              - distance
              - duration
              - routes_points
            properties:
              start_location:
                type: object
                required:
                - lat
                - lng
                properties:
                  lat:
                  # 小数点
                    type: number
                  lng:
                    type: number
              end_location:
                type: object
                required:
                - lat
                - lng
                properties:
                  lat:
                  # 小数点
                    type: number
                  lng:
                    type: number
              start_address:
                type: string
              end_address:
                type: string
              distance:
                type: integer
              duration:
                type: integer
              routes_points:
                type: array
                items:
                  type: string




    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string